"""Initial migration for chat history, user sessions, and ingestion records

Revision ID: f356bfc18dce
Revises: 261da0e15449
Create Date: 2025-12-09 19:30:55.527985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f356bfc18dce'
down_revision: Union[str, Sequence[str], None] = '261da0e15449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
