name: Continuous Embedding Update

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'docs/**/*.md' # Only run if book content changes

jobs:
  update_embeddings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rag-ingestion/requirements.txt # Assuming requirements.txt for ingestion scripts
          pip install -r rag-backend/requirements.txt # Assuming requirements.txt for backend client dependencies

      - name: Run Incremental Embedding Update
        run: python rag-ingestion/scripts/initial_ingestion.py # This script would be modified to handle incremental updates
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_HOST: ${{ secrets.QDRANT_HOST }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          QDRANT_COLLECTION_NAME: physical-ai-robotics-book-chunks
